"use client";

import { motion } from "framer-motion";
import { fadeUp, stagger } from "../components/anim";
import { Trophy, Users, Bot, BookOpenCheck, BadgeCheck } from "lucide-react";

type Stat = {
  label: string;
  value: string;
  icon: React.ReactNode;
};

const STATS: Stat[] = [
  { value: "$10,000,000+", label: "In profits generated by members", icon: <Trophy size={20} /> },
  { value: "100,000+", label: "Social Media Followers", icon: <Users size={20} /> },
  { value: "11+", label: "AI Money Making Methods", icon: <Bot size={20} /> },
  { value: "75+", label: "Online Course Subjects", icon: <BookOpenCheck size={20} /> },
  { value: "20+", label: "Years of Experience", icon: <BadgeCheck size={20} /> },
];

export default function StatsTiles() {
  return (
    <section id="stats" className="py-16 lg:py-24 border-t" style={{ borderColor: "var(--border)" }}>
      <div className="container-safe">
        <motion.div
          variants={stagger}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, amount: 0.35 }}
          className="grid gap-6"
        >
          <motion.h2 variants={fadeUp} className="text-3xl font-bold text-center">
            Proven by Numbers
          </motion.h2>

          <motion.p
            variants={fadeUp}
            className="text-center text-[color:var(--muted)] max-w-2xl mx-auto"
          >
            Real traction, real results — validated by our community.
          </motion.p>

          <motion.div
            variants={fadeUp}
            className="mt-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6"
          >
            {STATS.map((s) => (
              <article
                key={s.label}
                className="tile-card hover-card ring-1"
                style={{ borderColor: "var(--border)" }}
              >
                <div className="tile-inner">
                  <div className="icon-badge">
                    {s.icon}
                  </div>
                  <div className="mt-4">
                    <div className="text-2xl font-extrabold leading-none">{s.value}</div>
                    <div className="mt-2 text-sm text-[color:var(--muted)]">{s.label}</div>
                  </div>
                </div>
              </article>
            ))}
          </motion.div>
        </motion.div>
      </div>
    </section>
  );
}
