'use client';
import * as React from "react";
import { Trophy, Users, BrainCircuit, BookOpen, Award } from "lucide-react";
import { motion } from "framer-motion";
import { fadeUp, stagger } from "./anim";

type Item = {
  value: string;
  title: string;
  icon: React.ReactNode;
};

const items: Item[] = [
  { value: "$10,000,000+", title: "In profits generated by members", icon: <Trophy size={28} /> },
  { value: "100,000+", title: "Social Media Followers", icon: <Users size={28} /> },
  { value: "11+", title: "AI Money Making Methods", icon: <BrainCircuit size={28} /> },
  { value: "75+", title: "Online Course Subjects", icon: <BookOpen size={28} /> },
  { value: "20+", title: "Years of Experience", icon: <Award size={28} /> },
];

export default function StatsTiles(){
  return (
    <section id="stats" className="py-16 lg:py-24 border-t border-[var(--border)]">
      <div className="container-safe">
        <motion.h2
          initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.4 }}
          variants={fadeUp}
          className="text-3xl font-bold"
        >
          Proven by the Numbers
        </motion.h2>
        <motion.div
          variants={stagger}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, amount: 0.2 }}
          className="mt-8 grid sm:grid-cols-2 lg:grid-cols-5 gap-6"
        >
          {items.map((it)=> (
            <motion.div
              key={it.title}
              variants={fadeUp}
              className="rounded-2xl bg-[color:var(--surface)] ring-1 ring-[var(--border)] p-6 flex flex-col items-start gap-4 hover-card grad-border group"
            >
              <div className="rounded-xl p-3 ring-1 ring-[var(--border)] bg-[color:var(--bg)] transition-transform group-hover:scale-105">
                {it.icon}
              </div>
              <div>
                <div className="text-2xl font-bold leading-tight">{it.value}</div>
                <div className="text-sm text-[color:var(--muted)]">{it.title}</div>
              </div>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  )
}
